/* ═══════════════════════════════════════════════════════════════
   data.js — Mock 데이터
   ═══════════════════════════════════════════════════════════════ */

export const MOCK_RECORDS = [
  { id:"rec-1",title:"프로젝트 발표 준비",tasks:["발표 자료","리허설","제출"],taskCount:3,totalEstMin:120,totalActualMin:105,speedRank:"상위 15%",rankLevel:"fast",date:new Date("2026-03-28"),categories:["create","talk","digital"],breakdown:[{title:"자료 수집",estMin:20,actMin:18,cat:"digital",bt:"MECHANICAL"},{title:"슬라이드 작성",estMin:40,actMin:35,cat:"create",bt:"COGNITIVE"},{title:"리허설",estMin:30,actMin:28,cat:"talk",bt:"COGNITIVE"},{title:"제출",estMin:30,actMin:24,cat:"digital",bt:"MECHANICAL"}]},
  { id:"rec-2",title:"사무실 이동 + 미팅",tasks:["강남 이동","고객 미팅"],taskCount:2,totalEstMin:90,totalActualMin:95,speedRank:"평균",rankLevel:"avg",date:new Date("2026-03-25"),categories:["move","talk"],breakdown:[{title:"출발 준비",estMin:10,actMin:12,cat:"organize",bt:"ACTIVATION"},{title:"이동",estMin:40,actMin:45,cat:"move",bt:"MECHANICAL"},{title:"미팅",estMin:30,actMin:28,cat:"talk",bt:"COGNITIVE"},{title:"회의록",estMin:10,actMin:10,cat:"organize",bt:"MECHANICAL"}]},
  { id:"rec-3",title:"코드 리팩토링",tasks:["분석","리팩토링","테스트"],taskCount:3,totalEstMin:180,totalActualMin:150,speedRank:"상위 8%",rankLevel:"fast",date:new Date("2026-03-20"),categories:["digital","organize"],breakdown:[{title:"코드 분석",estMin:30,actMin:25,cat:"digital",bt:"EVALUATIVE"},{title:"계획",estMin:20,actMin:15,cat:"organize",bt:"EVALUATIVE"},{title:"구현",estMin:90,actMin:75,cat:"digital",bt:"COGNITIVE"},{title:"테스트",estMin:40,actMin:35,cat:"digital",bt:"EVALUATIVE"}]},
  { id:"rec-4",title:"블로그 포스트",tasks:["주제 선정","작성","편집","발행"],taskCount:4,totalEstMin:100,totalActualMin:110,speedRank:"평균",rankLevel:"avg",date:new Date("2026-03-15"),categories:["create","digital"],breakdown:[{title:"리서치",estMin:15,actMin:20,cat:"organize",bt:"MECHANICAL"},{title:"초안",estMin:45,actMin:50,cat:"create",bt:"COGNITIVE"},{title:"이미지 편집",estMin:20,actMin:25,cat:"digital",bt:"COGNITIVE"},{title:"발행",estMin:20,actMin:15,cat:"digital",bt:"MECHANICAL"}]},
  { id:"rec-5",title:"주간 보고서",tasks:["데이터 수집","보고서 작성"],taskCount:2,totalEstMin:60,totalActualMin:45,speedRank:"상위 10%",rankLevel:"fast",date:new Date("2026-04-01"),categories:["organize","create"],breakdown:[{title:"데이터 수집",estMin:20,actMin:15,cat:"digital",bt:"MECHANICAL"},{title:"초안 작성",estMin:25,actMin:20,cat:"create",bt:"COGNITIVE"},{title:"검토/제출",estMin:15,actMin:10,cat:"organize",bt:"EVALUATIVE"}]},
];
